headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\audri\\OneDrive\\PERSONAL PC 2024\\KRAULIS\\arunas-baskys-puslapis"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/images/*"

[headers.values]
Cache-Control = "public, max-age=86400"